<template>
  <div class="inicio">
    <b-button class="crear" variant="dark" to="/eventosRegistroA">
      Nuevo Evento
    </b-button>
    <div class="div">
      <div class="filtro">
        <b-dropdown
          id="dropdown-right"
          right
          text="Ordenar por..."
          variant="dark"
          class="m-2"
        >
          <b-dropdown-item href="#">Más reciente</b-dropdown-item>
          <b-dropdown-item href="#">Más antiguo</b-dropdown-item>
          <b-dropdown-item href="#">Orden alfabético</b-dropdown-item>
        </b-dropdown>
      </div>
      <div class="search-wrapper">
        <b-form-input type ="text" size="sm" class="mr-sm-2" placeholder="Buscar evento" v-model="search"
        @change="onChange" @keyup="onChange" @search="handleSearch"></b-form-input>
        <b-button size="sm" class="my-2 my-sm-0" type="submit" variant="dark">Search</b-button>
      </div>
    </div>
    <br>
    <div v-for="evento in eventosFiltrados" :key="evento.ID_Evento"></div>
      <Listar :eventos="eventos" />
  </div>
</template>

<script>
import Listar from "@/components/Eventos/Listar.vue";
export default {
  name: "EventosInicioA",
  data(){
    return{
      search: '',

    }
  },
  components: {
    Listar,
  },
  created() {
    // Llama una acción de la store, que se
    // va a completar de manera asíncrona
    this.$store.dispatch("setEventos");
  },
  computed: {
    // Obtiene los eventos del estado, que inicialmente es []
    eventos() { return this.$store.getters.getEventos },
    eventosFiltrados(){
      return this.eventos.filter(evento => evento.Nombre.includes(this.search));
    }
  },
  methods:{
    onChange(){
      this.$emit("search", this.search)
    },
    handleSearch(value){
      console.log(value)
    }
  }

}
</script>

<style scoped>
/* ----------------------------------------------
 * Generated by Animista on 2021-10-10 23:2:25
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-bottom
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-bottom {
  0% {
    -webkit-transform: translateY(1000px);
    transform: translateY(1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
}
@keyframes slide-in-bottom {
  0% {
    -webkit-transform: translateY(1000px);
    transform: translateY(1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
}

.crear {
  position: fixed;
  width: 30vw;
  bottom: 3%;
  left: 35vw;
  z-index: 2;

  animation-name: slide-in-bottom;
  animation-duration: 0.75s;
}

.inicio {
  position: relative;
}

.filtro {
  display: flex;
  justify-content: flex-end;
  width: 95vw;
}

.filtro > div {
  width: fit-content !important;
  margin-right: 2% !important;
}

body {
  align-items: center;
  padding-top: 40px;
  padding-bottom: 40px;
  background-color: #f3f3f3;
}

.nav-link {
  color: rgb(255, 255, 255);
}

.card-body {
  text-align: center;
}

.card-img-top {
  width: 45%;
  display: block;
  margin-left: auto;
  margin-right: auto;
  padding-bottom: 2em;
}

div.btn-group {
  width: 80%;
  display: block;
  margin-left: auto;
  margin-right: auto;
  padding-bottom: 1%;
  padding-top: 1%;
}

.btn-group a {
  background-color: black;
  border-color: black;
}

a .btn:hover {
  color: #f2f2f2 !important;
}

.dropdown-Nombre a {
  color: black;
}

.dropdown-Fecha a {
  color: black;
}

.dropdown-Evento a {
  color: black;
}

#toCrearEvento {
  min-height: 40px;
  min-width: 100px;
  border-radius: 20px;
  padding: 10px;
}

.sub-nav {
  display: flex;
  justify-content: space-around;
}

.sub-nav > * {
  flex-basis: 40%;
}

.transform-dropdown {
  transform: translate3d(8rem, 50px, 0px) !important;
}

.search-wrapper {
  padding-top: 1px; 
  padding-left: 15px;
  display: flex;
  justify-content: flex-end;
  width: 33vw;
}

</style>